//! Small constructors for restrictions emitted by the SAPIC translation.
//!
//! These formulas are generated by the translator, so routing them through
//! the surface parser only to lower them immediately added an avoidable second
//! representation and an impossible parse-error path.

use tamarin_term::intern::intern_str;
use tamarin_term::lterm::{BVar, LSort, LVar};
use tamarin_term::vterm::var_term;
use tamarin_theory::atom::ProtoAtom;
use tamarin_theory::fact::{Fact, FactTag, Multiplicity};
use tamarin_theory::formula::{exists_var, for_all_var, BLNTerm, LNFormula, ProtoFormula};
use tamarin_theory::restriction::Restriction;

pub(crate) fn msg(name: &str) -> LVar {
    LVar::new(name, LSort::Msg, 0)
}

pub(crate) fn node(name: &str) -> LVar {
    LVar::new(name, LSort::Node, 0)
}

pub(crate) fn indexed_node(name: &str, idx: u64) -> LVar {
    LVar::new(name, LSort::Node, idx)
}

fn term(v: LVar) -> BLNTerm {
    var_term(BVar::Free(v))
}

pub(crate) fn action(name: &str, args: &[LVar], at: LVar) -> LNFormula {
    let terms = args.iter().copied().map(term).collect::<Vec<_>>();
    let fact = Fact::new(
        FactTag::Proto(Multiplicity::Linear, intern_str(name), terms.len()),
        terms,
    );
    ProtoFormula::Atom(ProtoAtom::Action(term(at), fact))
}

pub(crate) fn eq(left: LVar, right: LVar) -> LNFormula {
    ProtoFormula::Atom(ProtoAtom::EqE(term(left), term(right)))
}

pub(crate) fn less(left: LVar, right: LVar) -> LNFormula {
    ProtoFormula::Atom(ProtoAtom::Less(term(left), term(right)))
}

pub(crate) fn all(vars: &[LVar], mut body: LNFormula) -> LNFormula {
    for var in vars.iter().rev() {
        body = for_all_var((var.name.to_string(), var.sort), var, body);
    }
    body
}

pub(crate) fn exists(vars: &[LVar], mut body: LNFormula) -> LNFormula {
    for var in vars.iter().rev() {
        body = exists_var((var.name.to_string(), var.sort), var, body);
    }
    body
}

pub(crate) fn restriction(name: impl Into<String>, formula: LNFormula) -> Restriction {
    Restriction {
        name: name.into(),
        formula,
        original_formula: None,
    }
}
