// Byte-exact page-shell scaffolding copied from observed oracle output
// (compatibility content per clean-room protocol).
// Parameter placeholders (section-sign delimited): NAME IDX VERSION FILENAME.

pub const PAGE_PREFIX: &str = r####"<!DOCTYPE html>
<html><head><title>Theory: §NAME§</title><link rel="stylesheet" href="/static/css/intdot-style.css"><link rel="stylesheet" href="/static/css/tamarin-prover-ui.css"><link rel="stylesheet" href="/static/css/jquery-contextmenu.css"><link rel="stylesheet" href="/static/css/smoothness/jquery-ui.css"><script src="/static/js/jquery.js"></script></script><script src="/static/js/jquery-ui.js"></script></script><script src="/static/js/jquery-layout.js"></script></script><script src="/static/js/jquery-cookie.js"></script></script><script src="/static/js/jquery-superfish.js"></script></script><script src="/static/js/jquery-contextmenu.js"></script></script><script src="/static/js/tamarin-prover-ui.js"></script></script><script type="module" src="/static/js/intdot-graph.es.js"></script></script><script type="module" src="/static/js/intdot-staticgraph.es.js"></script></script><script type="module" src="/static/js/intdot-dynamicgraph.es.js"></script></script></head><body><p class="loading">Analyzing, please wait...  <a id=cancel href='#'>Cancel</a></p><div class="ui-layout-north"><div class="layout-pane-north"><div id="header-info">Running <a href=/><span class="tamarin">Tamarin</span></a> §VERSION§</div></div><div id="header-links"><ul id="navigation"><li><a href=/>Index</a></li><li><form class="ajax-form ajax-form-full reload-confirm" method="POST" action="/thy/trace/§IDX§/reload"><button class="nav-button" type="submit">Reload file</button></form></li><li><a href="#">Actions</a><ul><li><a target=_blank href=/thy/trace/§IDX§/source>Show source</a></li><li><a href=/thy/trace/§IDX§/download/§FILENAME§>Download source</a></li><li><form class="ajax-form" method="POST" action="/thy/trace/§IDX§/get_and_append/§FILENAME§"><button class="link-button" type="submit">Append modified lemmas to file</button></form></li></ul></li><li><a href="#">Options</a><ul class="list-with-toggles"><li><a id=abbrv-toggle href="#">Abbreviate terms</a></li><li><a id=agent-toggle href="#">Clustering by role</a></li><li><a id=auto-toggle href="#">Show annotation auto-sources</a></li><li><a id=lvl0-toggle href="#">Graph simplification off</a></li><li><a id=lvl1-toggle href="#">Graph simplification L1</a></li><li><a id=lvl2-toggle href="#">Graph simplification L2</a></li><li><a id=lvl3-toggle href="#">Graph simplification L3</a></li></ul></li></ul></div></div><div class="ui-layout-west"><h1 class="pane-head">Proof scripts</h1><div class="scroll-wrapper" id="proof-wrapper"><div class="monospace" id="proof">"####;

pub const PAGE_MID: &str = r####"</div></div></div><div class="ui-layout-east"><h1 class="pane-head">&nbsp;Debug information</h1><div class="scroll-wrapper" id="debug-wrapper"><div id="ui-debug-display"></div></div></div><div class="ui-layout-center"><h1 class="pane-head" id="main-title">Visualization display</h1><div class="scroll-wrapper" id="main-wrapper" tabindex="0"><div id="ui-main-display">"####;

pub const PAGE_TAIL: &str = r####"</div></div></div><div id="dialog"></div><div id="confirm-dialog"></div><ul id="contextMenu"><li class="autoprove"><a href="#autoprove">Autoprove</a></a></li></ul></body></html>"####;
