[package]
name = "tamarin-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Utility library for the Tamarin prover (Rust port)."

[dependencies]
rustc-hash = { workspace = true }

[lints]
workspace = true
