#!/usr/bin/env bash
# RS-vs-HS performance benchmark → README-ready markdown tables.
#
# Runs each representative theory file through BOTH provers at several core
# counts, measuring wall-clock and peak resident memory.  Emits one markdown
# table per core count, wrapped in `<!-- BENCH:START -->` / `<!-- BENCH:END -->`
# markers, so the block can be dropped straight into the README.
#
#   scripts/bench.sh            # measure, print the block to stdout
#   scripts/bench.sh --write    # measure, then rewrite the block IN PLACE
#                                     #   between the markers in README.md
#
# Env knobs:
#   FILES        space-separated relpaths under examples/ (default: representative set)
#   CORES        space-separated core counts            (default: "1 4 16")
#   TIMEOUT      per-run wall-clock cap, seconds        (default: 600)
#   DERIV        --derivcheck-timeout passed to both    (default: 30)
#   HS_PATH / RS_PATH    override the prover binaries
#   README_PATH  file to rewrite in --write mode        (default: README.md)
#
# Methodology:
#   - Core control: HS `+RTS -Nk -RTS`; RS `--processors=k` (its Maude pool
#     defaults to max(1, k), a 1:1 workers:maudes ratio).  Both prove all
#     lemmas (`--prove`).
#   - "peak RSS" is the prover PROCESS only (/usr/bin/time -v "Maximum resident
#     set size").  Maude runs as separate subprocess(es) on BOTH sides and is
#     not counted — the comparison is GHC-heap vs Rust-heap.
#   - Single run per cell (wall-clock is noisy by ±10%; magnitudes are stable).
set -uo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
CORPUS="$repo_root/tamarin-prover/examples"
README_PATH="${README_PATH:-$repo_root/README.md}"
TIMEOUT="${TIMEOUT:-600}"
DERIV="${DERIV:-30}"
CORES="${CORES:-1 4 16}"
FILES="${FILES:-classic/NSPK3.spthy ake/bilinear/Joux.spthy features/auto-sources/tamarin-repo/sapic/statVerifLeftRight/stateverif_left_right.spthy sapic/fast/Yubikey/Yubikey.spthy accountability/csf21-acc-unbounded/mixvote/mixvote_SmHh-multi-session.spthy csf19-wrapping/gcm.spthy wireguard/wireguard.spthy features/auto-sources/spore/CCITT_X509_3.spthy}"

WRITE=0
for arg in "$@"; do
    case "$arg" in
        --write) WRITE=1 ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "bench.sh: unknown argument '$arg' (try --write or --help)" >&2; exit 2 ;;
    esac
done

find_hs() { ls "$repo_root"/tamarin-prover-testing/.stack-work/install/*/*/*/bin/tamarin-prover 2>/dev/null | head -1; }
HS_PATH="${HS_PATH:-$(find_hs)}"
RS_PATH="${RS_PATH:-$repo_root/target/release/tamarin-rs}"
[ -x "$HS_PATH" ] || { echo "bench.sh: no HS binary (set HS_PATH)" >&2; exit 2; }
[ -x "$RS_PATH" ] || { echo "bench.sh: no RS binary at $RS_PATH" >&2; exit 2; }
command -v /usr/bin/time >/dev/null || { echo "bench.sh: needs GNU /usr/bin/time" >&2; exit 2; }

# measure <cmd...> → prints "<secs>|<mb>" (or "timeout|—" on cap).
measure() {
    local e rc wall rss
    e=$(mktemp)
    timeout "$TIMEOUT" /usr/bin/time -v "$@" >/dev/null 2>"$e"; rc=$?
    if [ "$rc" = 124 ]; then rm -f "$e"; printf 'timeout|—'; return; fi
    wall=$(awk -F': ' '/Elapsed \(wall clock\)/{print $NF}' "$e")
    rss=$(awk -F': ' '/Maximum resident set size/{print $NF}' "$e")
    rm -f "$e"
    awk -v w="$wall" -v k="$rss" 'BEGIN{
        n=split(w,a,":");
        s=(n==3)? a[1]*3600+a[2]*60+a[3] : (n==2)? a[1]*60+a[2] : w;
        printf "%.1f|%.0f", s, k/1024 }'
}

cell_t() { [ "$1" = timeout ] && printf 'timeout' || printf '%s s' "$1"; }
cell_m() { [ "$1" = "—" ] && printf '—' || printf '%s MB' "$1"; }

# pct <rs> <hs> → " (-44%)" (RS vs HS; negative = lower).  Empty when either
# side is non-numeric (timeout / — / zero baseline) so no bogus % is shown.
pct() {
    awk -v rs="$1" -v hs="$2" 'BEGIN{
        if (rs !~ /^[0-9.]+$/ || hs !~ /^[0-9.]+$/ || hs+0==0) { exit }
        printf " (%+.0f%%)", (rs-hs)/hs*100 }'
}
# RS cells: value + parenthetical % vs the HS value in the same row.
cell_rs_t() { [ "$1" = timeout ] && printf 'timeout' || printf '%s s%s' "$1" "$(pct "$1" "$2")"; }
cell_rs_m() { [ "$1" = "—" ] && printf '—' || printf '%s MB%s' "$1" "$(pct "$1" "$2")"; }

# Emit the full marker block (header comment + per-core tables) to stdout.
gen_block() {
    # Static header comment.  Kept in sync with the README prose; this is the
    # single source of truth for "where do these numbers come from".
    cat <<'HDR'
<!-- BENCH:START — auto-generated by scripts/bench.sh; do not edit by hand.

Regenerate these three tables in place:

    scripts/bench.sh --write     # measure, then rewrite this block
    scripts/bench.sh             # measure, print to stdout only

Both provers prove every lemma (--prove --derivcheck-timeout=30); HS at
`+RTS -Nk`, RS at `--processors=k`; wall-clock + peak RSS come from
`/usr/bin/time -v` (the prover process only — Maude is a separate subprocess on
both sides and is excluded). Single run per cell (wall-clock is noisy ±10%).
The RS+HS columns measure ./prove_and_reverify.sh (THREADS=k): prove with RS,
then re-CHECK the emitted proofs with HS — i.e. the total cost of a proof you
did not have to trust the port for; its peak RSS is the max across both
phases. The RS+HS and RS columns show the % change vs HS in parentheses
(negative = faster / less memory). Tune the theory set / core counts /
binaries via the FILES, CORES, TIMEOUT, DERIV, HS_PATH, RS_PATH env vars (see
the scripts/bench.sh header).
-->
HDR
    echo "<!-- last run: $(uname -m) Linux, $(nproc) cores -->"
    for k in $CORES; do
        echo
        echo "**${k} core$([ "$k" = 1 ] && echo '' || echo 's')**"
        echo
        echo "| Theory | HS time | RS+HS time | RS time | HS memory | RS+HS memory | RS memory |"
        echo "|--------|--------:|-----------:|--------:|----------:|-------------:|----------:|"
        for f in $FILES; do
            af="$CORPUS/$f"
            base="${f##*/}"; base="${base%.spthy}"
            [ -f "$af" ] || { echo "| \`$base\` | (missing) | | | | | |"; continue; }
            h=$(measure "$HS_PATH" +RTS -N${k} -RTS --derivcheck-timeout="$DERIV" --prove "$af")
            r=$(measure "$RS_PATH" --processors="$k" --derivcheck-timeout="$DERIV" --prove "$af")
            p=$(measure env THREADS="$k" HS_PATH="$HS_PATH" RS_PATH="$RS_PATH" \
                    "$repo_root/prove_and_reverify.sh" "$af" --derivcheck-timeout="$DERIV")
            echo "| \`$base\` | $(cell_t "${h%|*}") | $(cell_rs_t "${p%|*}" "${h%|*}") | $(cell_rs_t "${r%|*}" "${h%|*}") | $(cell_m "${h#*|}") | $(cell_rs_m "${p#*|}" "${h#*|}") | $(cell_rs_m "${r#*|}" "${h#*|}") |"
        done
    done
    echo
    echo "<!-- BENCH:END -->"
}

block="$(gen_block)"

if [ "$WRITE" = 1 ]; then
    [ -f "$README_PATH" ] || { echo "bench.sh: no README at $README_PATH" >&2; exit 2; }
    grep -q '<!-- BENCH:START' "$README_PATH" || {
        echo "bench.sh: no <!-- BENCH:START --> marker in $README_PATH" >&2; exit 2; }
    grep -q '<!-- BENCH:END -->' "$README_PATH" || {
        echo "bench.sh: no <!-- BENCH:END --> marker in $README_PATH" >&2; exit 2; }
    bf=$(mktemp); printf '%s\n' "$block" > "$bf"
    tmp=$(mktemp)
    # Replace everything from the BENCH:START line through the BENCH:END line
    # (inclusive) with the freshly generated block, leaving the rest untouched.
    awk -v bf="$bf" '
        BEGIN { while ((getline line < bf) > 0) blk = blk line "\n" }
        /<!-- BENCH:START/ { printf "%s", blk; skip=1; next }
        /<!-- BENCH:END -->/ { skip=0; next }
        !skip { print }
    ' "$README_PATH" > "$tmp" && mv "$tmp" "$README_PATH"
    rm -f "$bf"
    echo "bench.sh: rewrote bench tables in $README_PATH" >&2
else
    printf '%s\n' "$block"
fi
